# Generated by Django 4.0.6 on 2022-07-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('date_published', models.DateTimeField(verbose_name='date published')),
                ('date_updated', models.DateTimeField(null=True, verbose_name='date updated')),
                ('content', models.TextField()),
                ('is_published', models.BooleanField()),
            ],
        ),
    ]
