# Generated by Django 4.0.6 on 2022-07-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='top_image',
            field=models.FilePathField(default=''),
        ),
    ]
