# Generated by Django 4.0.6 on 2022-07-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_top_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='top_image',
        ),
    ]
